#!/bin/bash

#./reuse_label.py "heart disease"
./reuse_label.py "asian food"
./reuse_label.py "jananese vehicle"
./reuse_label.py "arabic music"
./reuse_label.py "economy depression"
./reuse_label.py "artificial intelligence"
./reuse_label.py "american football club"
./reuse_label.py "american civil war"
./reuse_label.py "music holiday event"
./reuse_label.py "england football team"
./reuse_label.py "pacific coast highway"
./reuse_label.py "southern california freeway"
./reuse_label.py "hollywood movie star"
./reuse_label.py "information retrieval technique"
./reuse_label.py "university medical center doctor"
./reuse_label.py "software java platform support"
./reuse_label.py "apple store united states"
./reuse_label.py "traffic accident united states"
./reuse_label.py "computer science research conference"
./reuse_label.py "data mining research journal"
./reuse_label.py "second world war death"
./reuse_label.py "second world war atomic bomb"
#./reuse_label.py "financial aid university medical school"
./reuse_label.py "new york broadway singer poster"
./reuse_label.py "lincoln gun kill united states president"
