all:
#g++ main.cpp -std=c++0x -o search_doc 
#g++ optionC.cpp -std=c++0x -o optionC
#g++ optionA.cpp -std=c++0x -o optionA
#	g++ optionD.cpp -std=c++0x -o optionD
	g++ optionTest.cpp -std=c++0x -o optionTest
	g++ optionTest_ratioA.cpp -std=c++0x -o optionTest_ratioA
	g++ optionTest_ratioC.cpp -std=c++0x -o optionTest_ratioC
	g++ optionTestCluster_vector.cpp -std=c++0x -o optionTestCluster_vector
	g++ optionTestCluster.cpp -std=c++0x -o optionTestCluster
