all:
#g++ main.cpp -std=c++0x -o search_doc 
#g++ optionC.cpp -std=c++0x -o optionC
#g++ optionA.cpp -std=c++0x -o optionA
#	g++ optionD.cpp -std=c++0x -o optionD
	g++ optionTest.cpp -std=c++0x -o optionTest
	g++ optionTestCluster.cpp -std=c++0x -o optionTestCluster
